name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_REPOSITORY_NAME }} .
          docker tag ${{ secrets.DOCKER_REPOSITORY_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY_NAME }}:${{ secrets.DOCKER_REPOSITORY_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY_NAME }}:${{ secrets.DOCKER_REPOSITORY_TAG }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY_NAME }}:${{ secrets.DOCKER_REPOSITORY_TAG }}
            docker stop ${{ secrets.DOCKER_REPOSITORY_NAME }} || true
            docker rm ${{ secrets.DOCKER_REPOSITORY_NAME }} || true
            docker run -d --name ${{ secrets.DOCKER_REPOSITORY_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY_NAME }}:${{ secrets.DOCKER_REPOSITORY_TAG }}
